USE Spandana;
SHOW TABLES;
SELECT* FROM taxpayer;
SELECT* FROM income_category;
SELECT* FROM financial_year;
SELECT* FROM Income_Record;
SELECT UPPER(full_name) FROM taxpayer;
SELECT LOWER(occupation) FROM taxpayer;
SELECT full_name,LENGTH(full_name) FROM taxpayer;
SELECT SUBSTRING(pan_number,1,4) FROM taxpayer;
SELECT CONCAT(full_name,'-',occupation) FROM taxpayer;
SELECT REPLACE(category_name,'Income','Inc.') FROM income_category;
SELECT TRIM(full_name) FROM taxpayer;
SELECT SUBSTRING_INDEX(full_name,'',1) FROM taxpayer;
SELECT CONCAT('Taxpayer:',full_name,'Occupation:',occupation) FROM taxpayer;
SELECT* FROM taxpayer WHERE pan_number LIKE 'AP%';
SELECT full_name,ROUND(annual_income) FROM taxpayer;
SELECT full_name ,ROUND(annual_income,2) FROM taxpayer;
SELECT full_name,SQRT(annual_income) FROM taxpayer;
SELECT full_name,ABS(annual_income) FROM taxpayer;
SELECT MAX(annual_income) FROM taxpayer;
SELECT MIN(annual_income) FROM taxpayer;
SELECT MIN(annual_income) FROM taxpayer;
SELECT AVG(annual_income) FROM taxpayer;
SELECT SUM(annual_income) FROM taxpayer;
SELECT COUNT(*) FROM taxpayer;
SELECT full_name,POWER(annual_income,2) FROM taxpayer;
SELECT CURDATE();
SELECT NOW();
SELECT full_name,YEAR(date_of_birth) FROM taxpayer;
SELECT full_name,MONTH(date_of_birth) FROM taxpayer;
SELECT full_name,DAY(date_of_birth) FROM taxpayer;
SELECT full_name,TIMESTAMPDIFF(YEAR,date_of_birth,CURDATE())AS age FROM taxpayer;
SELECT year_label,DATE_ADD(start_date,INTERVAL 30 DAY)FROM financial_year;
SELECT year_label,DATE_SUB(end_date,INTERVAL 15 DAY)FROM financial_year;
SELECT year_label,DATEDIFF(end_date,start_date)FROM financial_year;
SELECT full_name ,DAYNAME(date_of_birth) FROM taxpayer;
SELECT full_name ,CAST(annual_income AS CHAR) FROM taxpayer;
SELECT income_id ,CAST(received_date AS CHAR) FROM Income_Record;
SELECT income_id ,DATE_FORMAT(received_date ,'%d-%m-%y') FROM Income_Record;
SELECT full_name ,DATE_FORMAT(date_of_birth ,'%m-%d-%y') FROM taxpayer;
SELECT full_name ,CAST(annual_income AS SIGNED) FROM taxpayer;
SELECT income_id ,DATE_FORMAT(received_date ,'%W-%M-%Y') FROM Income_Record;
SELECT UPPER(year_label) FROM financial_year;
SELECT LOWER(full_name) FROM taxpayer;
SELECT full_name,CONCAT('₹',annual_income) FROM taxpayer;
SELECT income_id ,CAST(YEAR(received_date) AS CHAR) FROM Income_Record;